export default Object.freeze({
  CHART_HEIGHT: 560,

  TRAFFIC_INCIDENTS: 'Traffic Incidents',
  TRAFFIC_FLOW_ISSUES: 'Traffic Flow Issues',
  SIGNAL_PERFORMANCE_ISSUES: 'Signal Issues',
  DEVICE_ANOMALIES: 'Device Anomalies',
  HIGH_CONGESTION_ROUTES: 'Congested Routes',
  REPORTED_WAZE_ALERTS: 'Waze Alerts',
  TRAFFIC_RESTRICTIONS: 'Traffic Restrictions',

  DEVICE_BLUETOOTH: 'Bluetooth Sensors',
  DEVICE_WEATHER: 'Weather Stations',
  DEVICE_RESTRICTIONS: 'Travel Restrictions',
  DEVICE_SEGMENTS: 'Anomaly Segments',

  TRAFFIC_INCIDENTS_ICON: 'mdi-car-multiple',
  DEVICE_TRAFFIC_ICON: 'mdi-traffic-cone',
  SIGNAL_PERFORMANCE_ISSUES_ICON: 'mdi-traffic-light',
  TRAFFIC_FLOW_ANOMALIES_ICON: 'mdi-alert-circle-outline',
  HIGH_CONGESTION_ROUTES_ICON: 'mdi-vector-line',
  REPORTED_WAZE_ALERTS_ICON: 'mdi-waze',
  DEVICE_CABINET_ICON: 'mdi-file-cabinet ',
  TRAFFIC_FLOW_ISSUES_ICON: 'mdi-road-variant',

  DEVICE_BLUETOOTH_ICON: 'mdi-bluetooth-connect',
  DEVICE_WEATHER_ICON: 'mdi-weather-cloudy',
  DEVICE_RESTRICTIONS_ICON: 'mdi-traffic-cone',
  DEVICE_WAZE_ICON: 'mdi-waze',
  DEVICE_ALERT_ICON: 'mdi-alert-circle-outline',
  DEVICE_SEGMENTS_ICON: 'mdi-vector-line',
  INFO_BAR_DEFAULT_COLOR: 'white',

  ADD_MAP_LAYER: 0,
  REMOVE_MAP_LAYER: 1,

  LAYER_DEVICE_TRAFFIC: 0,
  LAYER_DEVICE_BLUETOOTH: 1,
  LAYER_DEVICE_WEATHER: 2,
  LAYER_DEVICE_RESTRICTIONS: 3,
  LAYER_DEVICE_SEGMENTS: 4,
  LAYER_TOTAL_COUNT: 5,

  DATA_TRAFFIC_FLOW: 1,
  DATA_TRAVEL_TIME: 2,
  DATA_WAZE_ALERTS: 3,
  DATA_RESTRICTION: 4,
  DATA_WEATHER: 5,
  DATA_TRAFFIC_ALERT: 6,
  DATA_TRAFFIC_VIDEO: 7,

  CARD_DATA_INCIDENTS_ID: 0,
  CARD_DATA_RESTRICTIONS_ID: 1,
  CARD_DATA_SIGNAL_ISSUES_ID: 2,
  CARD_DATA_DEDVICE_ANOMALIES_ID: 3,
  CARD_DATA_CONGESTED_ROUTES_ID: 4,
  CARD_DATA_WAZE_ALERTS_ID: 5,
  CARD_DATA_FLOW_ANOMALIES_ID: 6
});
