export default Object.freeze({
  TRAFFIC_INCIDENTS: 'Traffic Incidents',
  SIGNAL_PERFORMANCE_ISSUES: 'Signal Issues',
  DEVICE_ANOMALIES: 'Device Anomalies',
  HIGH_CONGESTION_ROUTES: 'Congested Routes',
  REPORTED_WAZE_ALERTS: 'Waze Alerts',
  TRAFFIC_RESTRICTIONS: 'Traffic Restrictions',

  TRAFFIC_INCIDENTS_ICON: 'mdi-car-multiple',
  DEVICE_TRAFFIC_ICON: 'mdi-traffic-cone',
  SIGNAL_PERFORMANCE_ISSUES_ICON: 'mdi-traffic-light',
  HIGH_CONGESTION_ROUTES_ICON: 'mdi-vector-line',
  REPORTED_WAZE_ALERTS_ICON: 'mdi-waze',
  DEVICE_CABINET_ICON: 'mdi-file-cabinet ',

  CARD_DATA_INCIDENTS_ID: 0,
  CARD_DATA_RESTRICTIONS_ID: 1,
  CARD_DATA_SIGNAL_ISSUES_ID: 2,
  CARD_DATA_DEDVICE_ANOMALIES_ID: 3,
  CARD_DATA_CONGESTED_ROUTES_ID: 4,
  CARD_DATA_WAZE_ALERTS_ID: 5,
  CARD_DATA_FLOW_ANOMALIES_ID: 6
});
