// Generated by https://quicktype.io

export interface TravelTime {
    id:   string;
    name: string;
    data: Data;
}

export interface Data {
    travelTime:  GraphData;
    travelSpeed: GraphData;
}

export interface GraphData {
    data:     Datum[];
    xAxis:    string;
    yAxis:    string;
    title:    string;
    subtitle: string;
}

export interface Datum {
    name:  string;
    color: string;
    data:  Array<number[]>;
}
