micronaut:
  application:
    name: vms-backend
    version: 1.0.0
    description: Process API requests from VMS database
  server:
    port: 4003
    cors:
      enabled: true
    idle-timeout: 10h
    read-idle-timeout: 10h
    write-idle-timeout: 10h
  io:
    watch:
      paths: src/main
      restart: true